// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto_invoice/invoice.proto

package proto_invoice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvoiceData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId             int32    `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	ShippingCost         int32    `protobuf:"varint,5,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	FromLatitude         float64  `protobuf:"fixed64,6,opt,name=from_latitude,json=fromLatitude,proto3" json:"from_latitude,omitempty"`
	FromLongitude        float64  `protobuf:"fixed64,7,opt,name=from_longitude,json=fromLongitude,proto3" json:"from_longitude,omitempty"`
	ToLatitude           float64  `protobuf:"fixed64,8,opt,name=to_latitude,json=toLatitude,proto3" json:"to_latitude,omitempty"`
	ToLongitude          float64  `protobuf:"fixed64,9,opt,name=to_longitude,json=toLongitude,proto3" json:"to_longitude,omitempty"`
	Address              string   `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Status               int32    `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceData) Reset()         { *m = InvoiceData{} }
func (m *InvoiceData) String() string { return proto.CompactTextString(m) }
func (*InvoiceData) ProtoMessage()    {}
func (*InvoiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_21d14478728c648a, []int{0}
}

func (m *InvoiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceData.Unmarshal(m, b)
}
func (m *InvoiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceData.Marshal(b, m, deterministic)
}
func (m *InvoiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceData.Merge(m, src)
}
func (m *InvoiceData) XXX_Size() int {
	return xxx_messageInfo_InvoiceData.Size(m)
}
func (m *InvoiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceData.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceData proto.InternalMessageInfo

func (m *InvoiceData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InvoiceData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *InvoiceData) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *InvoiceData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InvoiceData) GetShippingCost() int32 {
	if m != nil {
		return m.ShippingCost
	}
	return 0
}

func (m *InvoiceData) GetFromLatitude() float64 {
	if m != nil {
		return m.FromLatitude
	}
	return 0
}

func (m *InvoiceData) GetFromLongitude() float64 {
	if m != nil {
		return m.FromLongitude
	}
	return 0
}

func (m *InvoiceData) GetToLatitude() float64 {
	if m != nil {
		return m.ToLatitude
	}
	return 0
}

func (m *InvoiceData) GetToLongitude() float64 {
	if m != nil {
		return m.ToLongitude
	}
	return 0
}

func (m *InvoiceData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InvoiceData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type InvoiceFilter struct {
	DriverId             int32    `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            int32    `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FromLatitude         float64  `protobuf:"fixed64,4,opt,name=from_latitude,json=fromLatitude,proto3" json:"from_latitude,omitempty"`
	FromLongitude        float64  `protobuf:"fixed64,5,opt,name=from_longitude,json=fromLongitude,proto3" json:"from_longitude,omitempty"`
	ToLatitude           float64  `protobuf:"fixed64,6,opt,name=to_latitude,json=toLatitude,proto3" json:"to_latitude,omitempty"`
	ToLongitude          float64  `protobuf:"fixed64,7,opt,name=to_longitude,json=toLongitude,proto3" json:"to_longitude,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceFilter) Reset()         { *m = InvoiceFilter{} }
func (m *InvoiceFilter) String() string { return proto.CompactTextString(m) }
func (*InvoiceFilter) ProtoMessage()    {}
func (*InvoiceFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_21d14478728c648a, []int{1}
}

func (m *InvoiceFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceFilter.Unmarshal(m, b)
}
func (m *InvoiceFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceFilter.Marshal(b, m, deterministic)
}
func (m *InvoiceFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceFilter.Merge(m, src)
}
func (m *InvoiceFilter) XXX_Size() int {
	return xxx_messageInfo_InvoiceFilter.Size(m)
}
func (m *InvoiceFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceFilter.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceFilter proto.InternalMessageInfo

func (m *InvoiceFilter) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *InvoiceFilter) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *InvoiceFilter) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *InvoiceFilter) GetFromLatitude() float64 {
	if m != nil {
		return m.FromLatitude
	}
	return 0
}

func (m *InvoiceFilter) GetFromLongitude() float64 {
	if m != nil {
		return m.FromLongitude
	}
	return 0
}

func (m *InvoiceFilter) GetToLatitude() float64 {
	if m != nil {
		return m.ToLatitude
	}
	return 0
}

func (m *InvoiceFilter) GetToLongitude() float64 {
	if m != nil {
		return m.ToLongitude
	}
	return 0
}

func (m *InvoiceFilter) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*InvoiceData)(nil), "InvoiceData")
	proto.RegisterType((*InvoiceFilter)(nil), "InvoiceFilter")
}

func init() {
	proto.RegisterFile("grpc/proto_invoice/invoice.proto", fileDescriptor_21d14478728c648a)
}

var fileDescriptor_21d14478728c648a = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xab, 0x40,
	0x14, 0x86, 0x2f, 0xdc, 0x16, 0xca, 0x81, 0xb2, 0x98, 0xc5, 0xbd, 0x93, 0xaa, 0x11, 0x6b, 0x4c,
	0xba, 0x82, 0x44, 0x9f, 0x40, 0x6b, 0x4c, 0x48, 0xba, 0xaa, 0x3b, 0x37, 0x04, 0x99, 0xb1, 0x4e,
	0x82, 0x1d, 0x32, 0x73, 0xe8, 0x63, 0xf8, 0x68, 0x3e, 0x93, 0x61, 0xa0, 0xc5, 0x6a, 0xd4, 0xae,
	0xe0, 0x7c, 0xf3, 0xcf, 0x9f, 0xcc, 0x97, 0x03, 0xd1, 0x4a, 0x55, 0x45, 0x52, 0x29, 0x89, 0x32,
	0x13, 0xeb, 0x8d, 0x14, 0x05, 0x4f, 0xba, 0x6f, 0x6c, 0xe8, 0xf4, 0xcd, 0x06, 0x3f, 0x6d, 0xc9,
	0x6d, 0x8e, 0x39, 0x09, 0xc1, 0x16, 0x8c, 0x5a, 0x91, 0x35, 0x1b, 0x2e, 0x6d, 0xc1, 0xc8, 0x7f,
	0x70, 0x6b, 0xcd, 0x55, 0x26, 0x18, 0xb5, 0x0d, 0x74, 0x9a, 0x31, 0x65, 0xe4, 0x08, 0x3c, 0xa6,
	0xc4, 0xa6, 0x3d, 0xfa, 0x6b, 0x8e, 0x46, 0x2d, 0x48, 0x19, 0x21, 0x30, 0x28, 0x24, 0xe3, 0x74,
	0x10, 0x59, 0x33, 0x6f, 0x69, 0xfe, 0xc9, 0x39, 0x8c, 0xf5, 0xb3, 0xa8, 0x2a, 0xb1, 0x5e, 0x65,
	0x85, 0xd4, 0x48, 0x87, 0xe6, 0x52, 0xb0, 0x85, 0x73, 0xa9, 0xb1, 0x09, 0x3d, 0x29, 0xf9, 0x92,
	0x95, 0x39, 0x0a, 0xac, 0x19, 0xa7, 0x4e, 0x64, 0xcd, 0xac, 0x65, 0xd0, 0xc0, 0x45, 0xc7, 0xc8,
	0x05, 0x84, 0x6d, 0x48, 0xae, 0x57, 0x6d, 0xca, 0x35, 0x29, 0x73, 0x75, 0xb1, 0x85, 0xe4, 0x14,
	0x7c, 0x94, 0x7d, 0xd3, 0xc8, 0x64, 0x00, 0xe5, 0xae, 0xe7, 0x0c, 0x82, 0x26, 0xb0, 0x6b, 0xf1,
	0x4c, 0xc2, 0x47, 0xd9, 0x77, 0x50, 0x70, 0x73, 0xc6, 0x14, 0xd7, 0x9a, 0x82, 0x79, 0xcb, 0x76,
	0x24, 0xff, 0xc0, 0xd1, 0x98, 0x63, 0xad, 0xa9, 0xdf, 0x7a, 0x69, 0xa7, 0xe9, 0xab, 0x0d, 0xe3,
	0x4e, 0xe8, 0x9d, 0x28, 0x91, 0xab, 0x7d, 0x53, 0xd6, 0x27, 0x53, 0xdf, 0xfa, 0x3d, 0x01, 0xa8,
	0x94, 0x64, 0x75, 0x81, 0xbd, 0x60, 0xaf, 0x23, 0x29, 0xfb, 0x2a, 0x6a, 0x70, 0x90, 0xa8, 0xe1,
	0x01, 0xa2, 0x9c, 0x5f, 0x45, 0xb9, 0x3f, 0x8a, 0x1a, 0xed, 0x89, 0xba, 0xbc, 0x86, 0xb0, 0xf3,
	0x71, 0xcf, 0xd5, 0x46, 0x14, 0x9c, 0x24, 0x30, 0x9e, 0x2b, 0x9e, 0x23, 0xef, 0x38, 0x09, 0xe3,
	0x3d, 0x63, 0x93, 0x20, 0xfe, 0xb0, 0x92, 0xd3, 0x3f, 0x37, 0xc7, 0x0f, 0x93, 0x44, 0xf3, 0xb2,
	0xe4, 0x2a, 0xe9, 0x17, 0x3a, 0xee, 0x16, 0xf9, 0xd1, 0x31, 0xe3, 0xd5, 0x7b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0x8f, 0x8f, 0x91, 0xed, 0x02, 0x00, 0x00,
}
