// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_seller/proto_product/product.proto

package proto_product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Qty                  int32    `protobuf:"varint,5,opt,name=qty,proto3" json:"qty,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductData) Reset()         { *m = ProductData{} }
func (m *ProductData) String() string { return proto.CompactTextString(m) }
func (*ProductData) ProtoMessage()    {}
func (*ProductData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7516bfb4bd1dfc42, []int{0}
}

func (m *ProductData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductData.Unmarshal(m, b)
}
func (m *ProductData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductData.Marshal(b, m, deterministic)
}
func (m *ProductData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductData.Merge(m, src)
}
func (m *ProductData) XXX_Size() int {
	return xxx_messageInfo_ProductData.Size(m)
}
func (m *ProductData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductData.DiscardUnknown(m)
}

var xxx_messageInfo_ProductData proto.InternalMessageInfo

func (m *ProductData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ProductData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductData) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductData) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *ProductData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type ProductFilter struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductFilter) Reset()         { *m = ProductFilter{} }
func (m *ProductFilter) String() string { return proto.CompactTextString(m) }
func (*ProductFilter) ProtoMessage()    {}
func (*ProductFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7516bfb4bd1dfc42, []int{1}
}

func (m *ProductFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductFilter.Unmarshal(m, b)
}
func (m *ProductFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductFilter.Marshal(b, m, deterministic)
}
func (m *ProductFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductFilter.Merge(m, src)
}
func (m *ProductFilter) XXX_Size() int {
	return xxx_messageInfo_ProductFilter.Size(m)
}
func (m *ProductFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ProductFilter proto.InternalMessageInfo

func (m *ProductFilter) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ProductData)(nil), "ProductData")
	proto.RegisterType((*ProductFilter)(nil), "ProductFilter")
}

func init() {
	proto.RegisterFile("grpc_seller/proto_product/product.proto", fileDescriptor_7516bfb4bd1dfc42)
}

var fileDescriptor_7516bfb4bd1dfc42 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x6d, 0x77, 0x5b, 0x71, 0xd4, 0x22, 0x41, 0x30, 0x78, 0x71, 0xa9, 0x88, 0x7b, 0x6a,
	0x44, 0xbf, 0x41, 0x11, 0x65, 0x6f, 0xb2, 0xde, 0xbc, 0x94, 0x9a, 0x0c, 0x12, 0xe8, 0x9a, 0x38,
	0x49, 0x85, 0x7e, 0x01, 0x3f, 0xb7, 0x24, 0xcd, 0xc1, 0x3f, 0xa7, 0xbc, 0xf7, 0x63, 0x66, 0x78,
	0x79, 0x70, 0xfd, 0x46, 0x56, 0x76, 0x0e, 0x87, 0x01, 0x49, 0x58, 0x32, 0xde, 0x74, 0x96, 0x8c,
	0x1a, 0xa5, 0x17, 0xe9, 0x6d, 0x22, 0xad, 0xbf, 0x32, 0x38, 0x7c, 0x9a, 0xc9, 0x7d, 0xef, 0x7b,
	0x56, 0x41, 0xae, 0x15, 0xcf, 0x56, 0xd9, 0xba, 0xd8, 0xe6, 0x5a, 0xb1, 0x33, 0xd8, 0x1f, 0x1d,
	0x52, 0xa7, 0x15, 0xcf, 0x23, 0x2c, 0x83, 0xdd, 0x28, 0xc6, 0x60, 0xf9, 0xde, 0xef, 0x90, 0x2f,
	0x56, 0xd9, 0xfa, 0x60, 0x1b, 0x35, 0x3b, 0x85, 0xc2, 0x92, 0x96, 0xc8, 0x97, 0x71, 0x74, 0x36,
	0xec, 0x04, 0x16, 0x1f, 0x7e, 0xe2, 0x45, 0x64, 0x41, 0x86, 0x5d, 0x85, 0x4e, 0xf2, 0x72, 0xde,
	0x0d, 0xba, 0xbe, 0x80, 0xe3, 0x94, 0xe3, 0x41, 0x0f, 0x1e, 0xe9, 0x6f, 0x92, 0xdb, 0x16, 0xaa,
	0x34, 0xf0, 0x8c, 0xf4, 0x19, 0x0e, 0xdf, 0x40, 0xf5, 0x88, 0x3e, 0xc1, 0x76, 0xda, 0x28, 0x56,
	0x35, 0xbf, 0x6e, 0x9c, 0x1f, 0x35, 0x3f, 0xfe, 0x56, 0xef, 0xb5, 0x57, 0x2f, 0x97, 0x42, 0x8e,
	0xce, 0x9b, 0x1d, 0x92, 0xf8, 0x57, 0x51, 0x93, 0xaa, 0x79, 0x2d, 0xa3, 0xbd, 0xfb, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x01, 0x10, 0x48, 0xa6, 0x46, 0x01, 0x00, 0x00,
}
