// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto_user/user.proto

package proto_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role                 uint32   `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Latitude             float64  `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fdc43824bd14e8a, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *UserData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserData) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UserData) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type UserFilter struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFilter) Reset()         { *m = UserFilter{} }
func (m *UserFilter) String() string { return proto.CompactTextString(m) }
func (*UserFilter) ProtoMessage()    {}
func (*UserFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fdc43824bd14e8a, []int{1}
}

func (m *UserFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFilter.Unmarshal(m, b)
}
func (m *UserFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFilter.Marshal(b, m, deterministic)
}
func (m *UserFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFilter.Merge(m, src)
}
func (m *UserFilter) XXX_Size() int {
	return xxx_messageInfo_UserFilter.Size(m)
}
func (m *UserFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFilter.DiscardUnknown(m)
}

var xxx_messageInfo_UserFilter proto.InternalMessageInfo

func (m *UserFilter) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*UserFilter)(nil), "UserFilter")
}

func init() {
	proto.RegisterFile("grpc/proto_user/user.proto", fileDescriptor_0fdc43824bd14e8a)
}

var fileDescriptor_0fdc43824bd14e8a = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x4d, 0xdd, 0xae, 0xdb, 0x29, 0x7a, 0x18, 0x04, 0x63, 0xd9, 0x43, 0xe9, 0xc5, 0x9e,
	0x5a, 0x50, 0xf0, 0x07, 0x2c, 0xa2, 0x78, 0xad, 0x78, 0xf1, 0x22, 0x71, 0x33, 0xac, 0x81, 0x6c,
	0x53, 0xa6, 0x59, 0xc1, 0x7f, 0xe4, 0xcf, 0x94, 0xa4, 0x68, 0x61, 0x2f, 0xe1, 0x7d, 0xef, 0xbd,
	0xc0, 0xcc, 0x40, 0xb1, 0xe3, 0x61, 0xdb, 0x0e, 0xec, 0xbc, 0x7b, 0x3f, 0x8c, 0xc4, 0x6d, 0x78,
	0x9a, 0xc8, 0xd5, 0x8f, 0x80, 0xd5, 0xeb, 0x48, 0xfc, 0xa0, 0xbc, 0xc2, 0x0b, 0x48, 0x8c, 0x96,
	0xa2, 0x14, 0x75, 0xda, 0x25, 0x46, 0x23, 0xc2, 0xa2, 0x57, 0x7b, 0x92, 0x49, 0x29, 0xea, 0xac,
	0x8b, 0x1a, 0x2f, 0x21, 0xa5, 0xbd, 0x32, 0x56, 0x9e, 0x46, 0x73, 0x82, 0xd0, 0x64, 0x67, 0x49,
	0x2e, 0x4a, 0x51, 0x9f, 0x77, 0x51, 0x87, 0xe6, 0xf0, 0xe9, 0x7a, 0x92, 0xe9, 0xd4, 0x8c, 0x80,
	0x05, 0xac, 0xac, 0xf2, 0xc6, 0x1f, 0x34, 0xc9, 0x65, 0x29, 0x6a, 0xd1, 0xfd, 0x33, 0xae, 0x21,
	0xb3, 0xae, 0xdf, 0x4d, 0xe1, 0x59, 0x0c, 0x67, 0xa3, 0x5a, 0x03, 0x84, 0x49, 0x1f, 0x8d, 0xf5,
	0xc4, 0xc7, 0xb3, 0xde, 0xde, 0x43, 0x1e, 0xd2, 0x17, 0xe2, 0x2f, 0xb3, 0x25, 0xbc, 0x81, 0xfc,
	0x89, 0x7c, 0x70, 0x36, 0xdf, 0xcf, 0x1a, 0xf3, 0x66, 0xfe, 0x5a, 0x64, 0xcd, 0xdf, 0xc6, 0xd5,
	0xc9, 0xe6, 0xfa, 0xed, 0xaa, 0x1d, 0xc9, 0x5a, 0xe2, 0x76, 0x3e, 0x53, 0x13, 0x2e, 0xf4, 0xb1,
	0x8c, 0xfa, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xe7, 0x96, 0x5c, 0x40, 0x01, 0x00, 0x00,
}
